markdown: kramdown
permalink: /:title/
url: http://wiilz.cn
name: Wiilz.CN
author: wiilz
qq: 
email: rayleignze@gmail.com
beian: 鲁ICP备17033500号-1
cnzz: 
weibo: 
github: wiilz
safe: true
paginate: 20
about: "这里是 Wiilz 的个人博客,使用Jekyll @ GitHub。<br /><br />新的折腾，新的起点。<br /><br />切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
