markdown: kramdown
permalink: /:title/
url: http://leungze.win
name: Wiilz.NET
author: Wiilz
qq: 
email: rayleignze@gmail.com
duoshuo: 
beian: 
cnzz: 
weibo: 
github: Wiilz
safe: true
paginate: 20
about: "这里是 Wiilz 的个人博客,使用Jekyll @ GitHub。<br /><br />新的折腾，新的起点。<br /><br />切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
